package com.pinkmoon.flux.db.category;

import androidx.room.Entity;
import androidx.room.PrimaryKey;

/**
 * A Category POJO (plain old Java object). This class models our Category
 * parent table (since a Task object cannot be inserted with a matching
 * foreign key from this table).
 */
@Entity(tableName = "table_category")
public class Category {

    @PrimaryKey(autoGenerate = true)
    private int categoryId;

    private String categoryName;

    /**
     * Constructor for the Category object that represents a table on our db.
     * Note again, the lack of categoryId within this constructor as it is
     * not necessary to pass this in ourselves since it is autogenerated
     * by room.
     * @param categoryName a value with the name of the parent category
     *                     for each task object.
     */
    public Category(String categoryName) {
        this.categoryName = categoryName;
    }

    public int getCategoryId() {
        return categoryId;
    }

    public void setCategoryId(int categoryId) {
        this.categoryId = categoryId;
    }

    public String getCategoryName() {
        return categoryName;
    }

    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }
}
